#!/usr/bin/env python
import sys
from pymatgen.apps.borg.hive import VaspToComputedEntryDrone
from pymatgen.apps.borg.queen import BorgQueen

# These three lines assimilate the data into ComputedEntries.
drone = VaspToComputedEntryDrone()
queen = BorgQueen(drone, sys.argv[1], 4)
#queen = BorgQueen(drone)
#queen.load_data("zintl_noPo.json")
#entries = queen.get_data()

# It's a good idea to perform a save_data, especially if you just assimilated
# a large quantity of data which took some time. This allows you to reload
# the data using a BorgQueen initialized with only the drone argument and
# calling queen.load_data(".json")
queen.save_data(sys.argv[2])

# These few lines generates the phase diagram using the ComputedEntries.

