#!/usr/bin/env python
import sys
from HighThroughput.communication.mysql import *

if len(sys.argv) == 4:
    extra = ' `stat` = ' + str(sys.argv[3])
else:
    extra = ' `leaf` = 1'

result = mysql_query('SELECT `jobid` FROM `calculations` WHERE `queue` = ' + str(sys.argv[1]) + ' AND `file` = ' + str(sys.argv[2]) + ' AND ' + extra)

if not isinstance(result,str):
    print(result['jobid'])
