#!/bin/bash
#Michael Sluydts 14/12/2011
walltime=$[$1-1]':59:00'

if [ $1 -gt 72 ]; then
    queue='special'
elif [ $1 -gt 12 ]; then
	queue='long'
elif [ $1 -eq 1 ]; then
	queue='debug'
else
	queue='short'
fi
#jobs='jobs'
if [ $VSC_INSTITUTE_CLUSTER == 'muk' ]; then
    queue='batch'
#    jobs='scripts'
fi

dir=`pwd`
cat > submit.sh << !
#!/bin/bash
#PBS -N $dir

#PBS -m ea

#PBS -q $queue

#PBS -l walltime=$walltime

#PBS -l nodes=1:ppn=1

cd $dir

module load pymatgen/2017.10.16-intel-2017b-Python-2.7.14
module load ase/3.8.1
module load HighThroughput/devel

HTphasedb $3 $4

exit 0
!

qsub submit.sh
