#!/usr/bin/env python
#HTrestart calcid or HTrestart queue file

import HighThroughput.manage.calculation as HT, sys,os
from HighThroughput.communication.mysql import mysql_query

if len(sys.argv) == 3:
    calc = mysql_query('SELECT `id` FROM `calculations` WHERE `queue` = ' + sys.argv[1] + ' AND `file` = ' + sys.argv[2] + ' AND `leaf` = 1')
else:
    calc = HT.get(sys.argv[1])

    if not isinstance(calc, str):
        HT.restart(calc['id'])
