#!/usr/bin/env python
#HTrestart calcid or HTrestart queue file

import HighThroughput.manage.calculation as HT, sys,os
from HighThroughput.communication.mysql import *

if len(sys.argv) == 4:
    calc = mysql_query('SELECT `id` FROM `calculations` WHERE `queue` = ' + sys.argv[1] + ' AND `file` = ' + sys.argv[2] + ' AND `leaf` = 1')
else:
    calc = HT.get(sys.argv[1])

if not isinstance(calc, basestring):
    HT.rollback(sys.argv[3], calc['id'])
