#!/usr/bin/env python
import HighThroughput as HT
import os,subprocess,sys
from HighThroughput.communication.mysql import *

server = ''

if len(sys.argv) >= 2:
    server = ' AND `queue` = ' + sys.argv[1] + ''

if len(sys.argv) == 3:
    server += ' AND `server` = \'' + os.getenv('VSC_INSTITUTE_CLUSTER') + '\''

running = mysql_query('SELECT COUNT(`id`) AS `count` FROM `calculations` WHERE `stat` % 2 = 1' + server)

print running['count']
