#!/usr/bin/env python
import sys
from operator import itemgetter
import math

def norm(l):
    return float(l[0])**2+float(l[1])**2+float(l[2])**2
f = open(sys.argv[1],'r')
poscar = f.readlines()

a = float(sys.argv[2])
def incell(l):
    sort = -(int(float(l[0]) <= a) + int(float(l[1]) <= a)  + int(float(l[2]) <= a))
    return sort
i=0
coords = []
for line in poscar:
    if i >= 8:
        coords.append(line.strip().split())
    i+= 1
coords = sorted(coords,key=norm)
coords = [' '.join(x) for x in coords]
text = ''.join(poscar[0:8]) + '\n'.join(coords)
print text
